# fly.toml app configuration file generated for fs-pokedex-xp on 2024-03-13T06:56:29+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fs-pokedex-xp'
primary_region = 'arn'

[build]

[env]
  PORT = "3000"

[processes]
  app = "node app.js"

[deploy]
  strategy = "bluegreen"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"
  check_response = "ok"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
