name: Deployment pipeline

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Lint, Build, and Test"]
    types:
      - completed

jobs:
  deploy_job:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}