name: Lint, Build, Test and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]


jobs:
  lint_build_test_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies 
        run: npm install  
      - name: Check style
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: Run end-to-end tests
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
  deploy_job:
    needs: lint_build_test_job
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-20.04
    steps:
      - name: Build
        run: npm run build

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy
        run: flyctl deploy --remote-only -a fs-pokedex-xp
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}