name: Lint, Build, Test and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]


jobs:
  lint_build_test_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies 
        run: npm install  
      - name: Check style
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: Run end-to-end tests
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
          

  deploy_job:
    needs: [lint_build_test_job]
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:

      - name: Check commit messages for skip
        uses: actions/github-script@v6.3.1
        id: check_skip
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        with: 
          result-encoding: string
          script: |
            var found = "false";
            const commitMessages = JSON.parse(process.env.COMMIT_MESSAGES);
            var messages = "";
            for (const msg of commitMessages) {
              messages += msg
            }
            if (messages.includes('#skip')) {
              found = "true"
            }
            return found;

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy
        if: ${{ steps.check_skip.outputs.result == 'true' }}
        run: flyctl deploy --remote-only -a fs-pokedex-xp
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  tag_release:
    needs: deploy_job
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch